```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(glmnet)
library(caret)
library(tidyverse)
library(ModelMetrics)
library(stats)
library(tree)
```



```{r}
# Load in data
bank <- read.csv("bankloan.csv")

# Remove ID Column
bank <- subset(bank, select = -c(ID, Experience))

# Clean data types
bank$CreditCard <- as.factor(bank$CreditCard)
bank$Online <- as.factor(bank$Online)
bank$CD.Account <- as.factor(bank$CD.Account)
bank$Securities.Account <- as.factor(bank$Securities.Account)
bank$Personal.Loan <- as.factor(bank$Personal.Loan)
bank$Education <- as.factor(bank$Education)
bank$Family <- as.factor(bank$Family)

# Create test and validation sets of data, using an 80/20 split.
test_fraction <- 0.2
random_subset <- sample.int(nrow(bank),
                            nrow(bank)*test_fraction) 
bank.train <- bank[-random_subset,]
bank.test <- bank[random_subset,]

# ENET model setup
x <- model.matrix(Personal.Loan~.-ZIP.Code, data=bank.train)[,-1]
y <- bank.train$Personal.Loan

# Original model
cv.ENET <- cv.glmnet(x, y, alpha=0.7, family="binomial")

# Determine best lambda value, create new model
ENET.mod <- glmnet(x, y, alpha=0.7, lambda=cv.ENET$lambda.min, family="binomial")

# Create predictions for model on unseen data, assign as 0 or 1.
probs <- predict(ENET.mod, newx=model.matrix(Personal.Loan~.-ZIP.Code, data=bank.test)[,-1])
ENET_Confusion_Matrix <- ifelse(probs<0.5, 0, 1)

# Original tree model
tree.fit <- tree(Personal.Loan~.-ZIP.Code, bank, subset=random_subset)

# Cross validation to prune tree
tree.fit.cv <- cv.tree(tree.fit, FUN = prune.misclass)

# Create new model with optimal number of leaves
tree.fit.cv.best <-  prune.misclass(tree.fit, best=tree.fit.cv$size[which.min(tree.fit.cv$dev)])

# Create confusion matrix for tree model
Tree_Confusion_Matrix <- predict(tree.fit.cv.best, bank.test, type="class")

```
